name: Build ARM rsync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi make wget libpopt-dev
        sudo apt-get install -y gcc g++ gawk autoconf automake python3-cmarkgfm
        sudo apt-get install -y acl libacl1-dev
        sudo apt-get install -y attr libattr1-dev
        sudo apt-get install -y libxxhash-dev
        sudo apt-get install -y libzstd-dev
        sudo apt-get install -y liblz4-dev
        sudo apt-get install -y libssl-dev
        
    - name: Install zlib
      run: |
        wget https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
        tar -xzvf zlib-1.2.13.tar.gz
        cd zlib-1.2.13
        CC=arm-linux-gnueabi-gcc ./configure --static
        make
        sudo make install
        
    - name: Download and extract rsync source code
      run: |
        wget https://download.samba.org/pub/rsync/src/rsync-3.2.7.tar.gz
        tar -xzvf rsync-3.2.7.tar.gz
        cd rsync-3.2.7

    - name: Build rsync for ARM with static linking
      run: |
        cd rsync-3.2.7
        CC=arm-linux-gnueabi-gcc CFLAGS="-static" ./configure --host=arm-linux-gnueabi
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rsync-arm-static
        path: rsync-3.2.7/rsync
