name: Build ARM64 rsync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu make wget libpopt-dev
        sudo apt-get install -y gcc g++ gawk autoconf automake python3-pip
        sudo apt-get install -y acl libacl1-dev
        sudo apt-get install -y attr libattr1-dev
        sudo apt-get install -y libxxhash-dev
        sudo apt-get install -y libzstd-dev
        sudo apt-get install -y liblz4-dev
        sudo apt-get install -y libssl-dev
        python3 -m pip install --user commonmark

    - name: Install zlib
      run: |
        wget https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
        tar -xzvf zlib-1.2.13.tar.gz
        cd zlib-1.2.13
        CC=aarch64-linux-gnu-gcc ./configure --static
        make
        sudo make install

    - name: Install xxhash
      run: |
        wget https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.1.tar.gz
        tar -xzvf v0.8.1.tar.gz
        cd xxHash-0.8.1
        CC=aarch64-linux-gnu-gcc make
        sudo make install

    - name: Install zstd
      run: |
        wget https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz
        tar -xzvf zstd-1.5.2.tar.gz
        cd zstd-1.5.2
        CC=aarch64-linux-gnu-gcc make
        sudo make install

    - name: Install lz4
      run: |
        wget https://github.com/lz4/lz4/archive/refs/tags/v1.9.3.tar.gz
        tar -xzvf v1.9.3.tar.gz
        cd lz4-1.9.3
        CC=aarch64-linux-gnu-gcc make
        sudo make install

    - name: Download and extract rsync source code
      run: |
        wget https://download.samba.org/pub/rsync/src/rsync-3.2.7.tar.gz
        tar -xzvf rsync-3.2.7.tar.gz
        cd rsync-3.2.7

    - name: Download and extract OpenSSL 3.3.1 source code
      run: |
        wget https://github.com/openssl/openssl/releases/download/openssl-3.3.1/openssl-3.3.1.tar.gz
        tar -xzvf openssl-3.3.1.tar.gz

    - name: Configure and build OpenSSL for ARM64
      run: |
        cd openssl-3.3.1
        CC=/usr/bin/aarch64-linux-gnu-gcc ./Configure linux-aarch64 --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
        make
        sudo make install

    - name: Build rsync for ARM64 with static linking
      run: |
        cd rsync-3.2.7
        export CFLAGS="-I/usr/local/openssl/include"
        export LDFLAGS="-L/usr/local/openssl/lib -Wl,-rpath,/usr/local/openssl/lib"
        export PKG_CONFIG_PATH="/usr/local/openssl/lib/pkgconfig"
        CC=aarch64-linux-gnu-gcc CFLAGS="-static" ./configure --host=aarch64-linux-gnu --with-included-popt --with-included-zlib --with-openssl=/usr/local/openssl
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rsync-arm64-static
        path: rsync-3.2.7/rsync
