name: Build ARM rsync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi make wget

    - name: Download and extract rsync source code
      run: |
        wget https://download.samba.org/pub/rsync/src/rsync-3.1.2.tar.gz
        tar -xzvf rsync-3.1.2.tar.gz
        cd rsync-3.1.2

    - name: Build rsync for ARM with static linking
      run: |
        cd rsync-3.1.2
        CC=arm-linux-gnueabi-gcc ./configure --host=arm-linux-gnueabi --disable-shared --enable-static
        make CFLAGS="-static"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rsync-arm-static
        path: rsync-3.1.2/rsync
